### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'poll'

### ISSUE THREAD

**Issue by savithakj** [gushitong/python-libzmap#2]
>>> from libzmap import ZmapProcess
>>> proc = ZmapProcess(targets='101.200.188.97/20', options='-B 100M', probe_module='icmp_echoscan')
>>> proc.stop()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "build/bdist.linux-x86_64/egg/libzmap/libzmap.py", line 162, in stop
AttributeError: 'NoneType' object has no attribute 'poll'

**Comment by gushitong** [comment]
You should call `proc.run()` before `proc.stop()`, which will initialize a zmap process.

```
def run(self):                                                                 
        cmdline = self.get_commandline()                                           
        try:                                                                       
            self.__zmap_proc = subprocess.Popen(args=shlex.split(cmdline), stdout=subprocess.PIPE,
                                                stderr=subprocess.PIPE,            
                                                universal_newlines=True, bufsize=0)
        except OSError, e:                                                         
            print(e)                                                               
            raise EnvironmentError(1, "zmap is not installed or could not be found in system path")
```
